name: wordly
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.3.0
  flutter_svg: ^2.0.17
  flutter_animate: ^4.5.2
  lottie: ^3.3.1
  showcaseview: ^4.0.1
  flutter_launcher_icons: ^0.14.3
  shared_preferences: ^2.2.2
  posthog_flutter: ^4.10.4
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.4
  uuid: ^4.5.1
  cloud_firestore: ^5.6.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path: "assets/appicons/app_logo.png"
  android: true

  web:
    generate: true



  min_sdk_android: 21

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/appicons/
    # - assets/appicons/android/
    - .env
    - assets/
    - assets/category/
    - assets/category/finance/
    - assets/category/plants/
    - assets/category/entertainment/
    - assets/category/bollywood/
    - assets/category/food/
    - assets/category/places/
    - assets/category/socialmedia/
    - assets/category/sports/
    - assets/category/technology/
    - assets/backspace.svg
    - assets/win.json
    # - assets/tick.json
    - assets/tick_two.json
    - assets/win_cup.svg
    - assets/you_win.svg
    - assets/logosvg.svg
    - assets/stars.svg
    - assets/singlestar.svg
    - assets/blue_circle.svg
    - assets/pink_circle.svg
    - assets/charw.svg
    - assets/charr.svg
    - assets/chare.svg
    - assets/star_two.svg
    - assets/peach_circle.svg
    - assets/wordly_name_logo.svg
    - assets/sad_emoji_two.png
    - assets/logo_png.png
    - assets/streak.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
